# Docker Compose file for ELK stack
# Customized for laszlo462's Rancher environment

version: '2'
volumes:
  elktest:
    driver: rancher-nfs
services:
  elktest:
    image: laszlo462/elk-docker:opnsense-dev
    volumes:
    - elktest:/var/lib/elasticsearch
    ports:
    - 5601:5601/tcp
    - 9200:9200/tcp
    - 5044:5044/tcp
    - 5014:5014/udp
    - 5014:5014/tcp
    labels:
      io.rancher.container.pull_image: always
